# Generated by Django 4.2.4 on 2023-09-09 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_image', models.ImageField(upload_to='images/')),
                ('major', models.CharField(max_length=1000)),
                ('job_title', models.CharField(max_length=2048)),
                ('city', models.CharField(max_length=2048)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('description', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
