# Generated by Django 4.2.4 on 2023-09-09 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='is_accepted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='is_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
