# Generated by Django 4.2.4 on 2023-09-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_specialistprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='specialistprofile',
            name='twitter',
        ),
    ]
