# Generated by Django 4.2.4 on 2023-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_specialistprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='linked_in',
            field=models.URLField(blank=True),
        ),
    ]
