# Generated by Django 4.2.4 on 2023-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_specialistprofile_accepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistprofile',
            name='accepet',
            field=models.BooleanField(blank=True),
        ),
    ]
