# Generated by Django 4.2.4 on 2023-09-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='times',
            new_name='selected_time',
        ),
    ]
