# Generated by Django 4.2.4 on 2023-09-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_times_request_selected_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
