# Generated by Django 4.2.4 on 2023-09-10 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_specialistprofile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=[('17-09-2023', '17-09-2023'), ('18-09-2023', '19-09-2023'), ('19-09-2023', '19-09-2023'), ('20-09-2023', '20-09-2023'), ('21-09-2023', '21-09-2023'), ('22-09-2023', '22-09-2023')], max_length=128)),
                ('times', models.CharField(choices=[('8:00', '8:00 Am'), ('9:00', '9:00 Am'), ('10:00', '10:00 Am'), ('11:00', '11:00 Am'), ('12:00', '12:00 Pm'), ('4:00', '4:00 Pm'), ('6:00', '6:00 Pm'), ('7:00', '7:00 Pm'), ('8:00', '8:00 Pm')], max_length=128)),
                ('Appointment_description', models.TextField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specialistprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
