# Generated by Django 4.2.4 on 2023-09-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialists', '0003_appointmentbooking_zoom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='times',
            field=models.CharField(choices=[('8:00', '8:00 am'), ('9:00', '9:00 am'), ('10:00', '10:00 am'), ('11:00', '11:00 am'), ('12:00', '12:00 pm'), ('4:00', '4:00 pm'), ('6:00', '6:00 pm'), ('7:00', '7:00 pm'), ('8:00', '8:00 pm')], max_length=128),
        ),
    ]
