# Generated by Django 4.2.4 on 2023-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_appointmentbooking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='zoom_password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
