# Generated by Django 4.2.4 on 2023-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_appointmentbooking_zoom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='times',
            field=models.CharField(choices=[('8:00 am', '8:00 am'), ('9:00 am', '9:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('12:00 pm', '12:00 pm'), ('4:00 pm', '4:00 pm'), ('6:00 pm', '6:00 pm'), ('7:00 pm', '7:00 pm'), ('8:00 pm', '8:00 pm')], max_length=128),
        ),
    ]
