# Generated by Django 4.2.4 on 2023-09-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=2048)),
                ('game_image', models.ImageField(upload_to='images/')),
                ('game_description', models.TextField()),
                ('game_url_appstore', models.URLField()),
                ('game_play_store', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=2048)),
                ('game_image', models.ImageField(upload_to='images/')),
                ('game_description', models.TextField()),
                ('game_url', models.URLField()),
            ],
        ),
    ]
