# Generated by Django 4.2.4 on 2023-09-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
