# Generated by Django 4.2.4 on 2023-09-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_center_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Khobar', 'Khobar'), ('Mecca', 'Mecca')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
