# Generated by Django 4.2.4 on 2023-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_center_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttour',
            name='time',
            field=models.TimeField(choices=[('8:00', '8:00'), ('8:00', '8:00'), ('8:00', '8:00'), ('8:00', '8:00')], max_length=128),
        ),
    ]
