# Generated by Django 4.2.4 on 2023-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_alter_requesttour_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Start'), (5, '5 Start')], max_length=128),
        ),
    ]
