# Generated by Django 4.2.4 on 2023-09-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttour',
            name='time',
        ),
        migrations.AddField(
            model_name='requesttour',
            name='times',
            field=models.CharField(choices=[('8:00', '8:00 am'), ('9:00', '9:00 am'), ('10:00', '10:00 am'), ('11:00', '11:00 am')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
