# Generated by Django 4.2.4 on 2023-09-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_remove_employee_image_employee_employeeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_image', models.ImageField(upload_to='images/')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
            ],
        ),
    ]
