# Generated by Django 4.2.4 on 2023-09-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_centeremployee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centeremployee',
            old_name='employee_name',
            new_name='employees_names',
        ),
    ]
