# Generated by Django 4.2.4 on 2023-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='location',
            field=models.URLField(max_length=1024),
        ),
    ]
